<h2> CV rating </h2>

In [1]:
import glob
CVs=glob.glob("CV_Word\*.docx")

## 1. Reading Data and preparing for process

In [2]:
import numpy as np
import pandas as pd
my_df = pd.DataFrame()

In [3]:
def create_data2(filename):
    #ilename1=filename.replace('_', ' ')
    filename1=filename[8:]
    filename1=filename1.replace('.docx', '')
    my_text = docx2txt.process(filename)
    my_df = pd.DataFrame()
    my_df = pd.DataFrame(data=[filename1],columns=['Name'])
    # using split() 
    # to extract words from string 
    res = my_text.split('\n\n') 
    kk=''
    cnt=0
    for t in res:
        cnt=cnt+1
        if t=='Contact':
            kk=''
            cnt2=cnt
            for t in res:  
                kk=kk+res[cnt2]
                cnt2=cnt2+1
                if res[cnt2]=='':
                    my_df['Contact'] =kk
                    break 
        if "Top Skills" in t:
            cnt2=cnt
            kk=''
            for t in res:
                kk=kk+res[cnt2]
                cnt2=cnt2+1
                if res[cnt2]=='':
                    my_df['Top_Skills'] =kk
                    break
        if t=='Languages':
            cnt2=cnt
            kk=''
            for t in res:      
                kk=kk+res[cnt2]
                cnt2=cnt2+1
                if res[cnt2]=='':
                    my_df['Languages'] =kk
                    break
        if t=='Certifications':
            cnt2=cnt
            kk=''
            for t in res:      
                kk=kk+res[cnt2]
                cnt2=cnt2+1
                if res[cnt2]=='':
                    my_df['Certifications'] =kk
                    break
        if t==filename1:
            cnt2=cnt
            kk=''
            for t in res:      
                kk=kk+res[cnt2]
                cnt2=cnt2+1
                if res[cnt2]=='':
                    my_df['Designation'] =kk
                    break  
        if t=='Summary':
            cnt2=cnt
            kk=''
            for t in res:
                kk=kk+res[cnt2]
                cnt2=cnt2+1
                if res[cnt2]=='':
                    my_df['Summary'] =kk
                    break
        if t=='Experience':
            cnt2=cnt
            kk=''
            for t in res:           
                kk=kk+res[cnt2]
                cnt2=cnt2+1
                if cnt2+1 > len(res):
                    my_df['Experience'] =kk
                    break
                else:
                    if res[cnt2]=='Education':
                        my_df['Experience'] =kk
                        break
        if t=='Education':
            cnt2=cnt
            kk=''
            for t in res:      
                kk=kk+res[cnt2]
                cnt2=cnt2+1
                if res[cnt2]=='':
                    my_df['Education'] =kk
                    break
     
        if 'Contact' in my_df.columns:
            str='ok'
        else:
            my_df['Contact'] ='' 
        if 'Top_Skills' in my_df.columns:
            str='ok'
        else:
            my_df['Top_Skills'] ='No Skill'
        if 'Languages' in my_df.columns:
            str='ok'
        else:
            my_df['Languages'] =''
        if 'Certifications' in my_df.columns:
            str='ok'
        else:
            my_df['Certifications'] =''
        if 'Summary' in my_df.columns:
            str='ok'
        else:
            my_df['Summary'] =''
        if 'Designation' in my_df.columns:
            str='ok'
        else:
            my_df['Designation'] =''
        if 'Experience' in my_df.columns:
            str='ok'
        else:
            my_df['Experience'] =''
        if 'Education' in my_df.columns:
            str='ok'
        else:
            my_df['Education'] =''
            
    my_df1=my_df.values.tolist()
    return my_df1,filename1

In [4]:
import numpy as np
import pandas as pd
import docx2txt
final_df =[]
for cvs in CVs:
    ret_df,name=create_data2(cvs)
    if len(ret_df)!=0:
        final_df.append(ret_df[0])

In [5]:
ddfff = pd.DataFrame(final_df,columns=['Name','Contact','Top_Skills','Language','Certifications','Summary','Designation','Experience','Education'])

In [6]:
ddfff

,Name,Contact,Top_Skills,Language,Certifications,Summary,Designation,Experience,Education
0,Abir Chowdhury,8274947096 (Mobile)abir30588@gmail.comwww.link...,Peoplesoft Time & Labor,Hindi (Elementary) English (Full Professional)...,Oracle Global Human Resources Cloud 2017 Certi...,\tHaving over 6 years of IT and relevant exper...,"Peoplesoft Developer Bengaluru, Karnataka, India",OracleSenior Application EngineerJuly 2019 - P...,West Bengal University of TechnologyMaster of ...
1,Ananya Brata Datta,dananyabrata@gmail.comwww.linkedin.com/in/anan...,Client Issue Resolution Team Management Progra...,,,Accomplished Oracle ERP Consultant with over 8...,"Team Lead at SOAIS Kolkata Area, India",SOAISTeam LeadFebruary 2012 - Present Kolkata ...,Pailan College Of Management and Technology Ma...
2,Chandan Sinha Roy,gcettbcse@gmail.comwww.linkedin.com/in/chandan...,No Skill,,,"Hi, I am Chandan Sinha Roy, Assistant Professo...","Training & Placement In Charge , Department of...",Government College of Engineering and Textile ...,
3,Chiranjit Nath,+919339814096 (Home)chiran2007@gmail.comwww.li...,Project Management Mobile Applications Website...,English (Native or Bilingual) Bengali (Native ...,,Having 10 years experience in Software Industr...,"Managing Director, CEO, Architect and Digital ...",IDIOSYS TECH PRIVATE LIMITEDDirectorMarch 2016...,
4,Debashis Debata,09903505848 (Home)debashisdebata104@gmail.comw...,,,,Experienced Senior Software Engineer with a de...,"Senior Software Engineer at SOAIS Kolkata, Wes...",SOAIS8 years 6 monthsSenior Software Engineer ...,"Orissa Engineering College (OEC), BhubaneswarB..."
5,Debdeep Basu,"44,Sibtala Lane, Shibpur Howrah-711102West Ben...",,,, Having 4+ year of PeopleSoft experience. Ex...,"Senior Software Engineer at SOAIS Bengaluru, K...",Tata Consultancy ServicesIT AnalystMay 2019 - ...,MCKV Institute of Engineering 116Master of Com...
6,Manish Bahety,+91 9331888299 (Mobile)bahety.manish@gmail.com...,Service Delivery,,,\tEighteen plus years of professional experien...,"Practice Director at SOAIS Bengaluru, Karnatak...",SOAISPractice Director December 2018 - Present...,FMS - Indian Institute of Rural ManagementPGDB...
7,Nayan Paul,"Kolkata , India+919932977549 (Mobile)nayanmail...",,,,,Consultant Enterprise Solutions (PeopleSoft HC...,www.dbtutor.comFounder & PeopleSoft BloggerFeb...,West Bengal University of Technology\t(2005 - ...
8,Partha Sarathi,parthasarathimondal@gmail.c omwww.linkedin.com...,Oracle SQL PL/SQL,,,,Advisory Technical Services Specialist at IBM ...,IBM India Private LimitedAdvisory Technical Se...,
9,Prashant Shetty,+919880577658 (Mobile)prashant.shettyy@gmail.c...,Project Management OracleSOA,,Oracle Cloud Customer Connect – Green Ribbon M...,Am an energetic and passionate professional co...,,SOAISVice President August 2008 - Present Beng...,T.A.PAI MANAGEMENT INSTITUTE
10,Samapti Bandyopadhyay,sammca1992@gmail.comwww.linkedin.com/in/samapt...,SQLPeopleTools XML Publisher,English (Full Professional) Bengali (Native or...,,Having 3 years of IT experience of which 2 yea...,"Senior Software Engineer at SOAIS Kolkata, Wes...",SOAISSenior Software Engineer December 2018 - ...,"University Of North BengalMaster’s Degree, Com..."
11,Sandip Das,9038647057 (Work)sandip.sandip.das5@gmail.co m...,LanguagesEnglish (Full Professional) Bengali (...,English (Full Professional) Bengali (Native or...,Introduction to Kali LinuxBecome a Full-Stack ...,"\tI'm a driven, energetic and proactive tech p...",,Independent ContractorSr. Javascript Developer...,Indira Gandhi National Open UniversityMaster o...
12,Santanu Pakhira,9433988990 (Home)santanu_m143@rediffmail.comww...,C,,,,"Mobile Application Developer Kolkata Area, India",Tata Consultancy ServicesIT AnalystSeptember 2...,
13,Sourav Pal,sourav.en@gmail.comwww.linkedin.com/in/sourav-...,DB2Requirements Analysis Pre-sales,English (Full Professional)\nSourav PalOracle ...,Oracle Applications Cloud Operations 2017 Impl...,Senior HCM CONSULTANT(Oracle HCM cloud -> Core...,,SOAIS2 years 10 monthsProject Manager December...,"West Bengal University of Technology, KolkataM..."

In [7]:
ddfff.to_csv('cv_details_org.csv')

In [8]:
ddfff=pd.read_csv('cv_details_org.csv')

In [9]:
ddfff.head(3)

,Unnamed: 0,Name,Contact,Top_Skills,Language,Certifications,Summary,Designation,Experience,Education
0,0,Abir Chowdhury,8274947096 (Mobile)abir30588@gmail.comwww.link...,Peoplesoft Time & Labor,Hindi (Elementary) English (Full Professional)...,Oracle Global Human Resources Cloud 2017 Certi...,\tHaving over 6 years of IT and relevant exper...,"Peoplesoft Developer Bengaluru, Karnataka, India",OracleSenior Application EngineerJuly 2019 - P...,West Bengal University of TechnologyMaster of ...
1,1,Ananya Brata Datta,dananyabrata@gmail.comwww.linkedin.com/in/anan...,Client Issue Resolution Team Management Progra...,NaN,NaN,Accomplished Oracle ERP Consultant with over 8...,"Team Lead at SOAIS Kolkata Area, India",SOAISTeam LeadFebruary 2012 - Present Kolkata ...,Pailan College Of Management and Technology Ma...
2,2,Chandan Sinha Roy,gcettbcse@gmail.comwww.linkedin.com/in/chandan...,No Skill,NaN,NaN,"Hi, I am Chandan Sinha Roy, Assistant Professo...","Training & Placement In Charge , Department of...",Government College of Engineering and Textile ...,NaN

In [10]:
ddfff.drop(['Unnamed: 0', 'Contact','Language', 'Certifications','Designation','Education'], axis=1,inplace=True)

In [11]:
ddfff.fillna('No Data',inplace=True)

In [12]:
import re
import string
import nltk
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize
stemmer= PorterStemmer()

stop_words = set(stopwords.words('english'))
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize
lemmatizer=WordNetLemmatizer()

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Anup\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Anup\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Anup\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [13]:
import re

def decontracted(phrase):
    # specific
    phrase = re.sub(r"won't", "will not", phrase)
    phrase = re.sub(r"can\'t", "can not", phrase)

    # general
    phrase = re.sub(r"n\'t", " not", phrase)
    phrase = re.sub(r"\'re", " are", phrase)
    phrase = re.sub(r"\'s", " is", phrase)
    phrase = re.sub(r"\'d", " would", phrase)
    phrase = re.sub(r"\'ll", " will", phrase)
    phrase = re.sub(r"\'t", " not", phrase)
    phrase = re.sub(r"\'ve", " have", phrase)
    phrase = re.sub(r"\'m", " am", phrase)
    return phrase

In [14]:
# we are removing the words from the stop words list: 'no', 'nor', 'not'
stopwords= ['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've",\
            "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', \
            'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their',\
            'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', \
            'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', \
            'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', \
            'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after',\
            'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further',\
            'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more',\
            'most', 'other', 'some', 'such', 'only', 'own', 'same', 'so', 'than', 'too', 'very', \
            's', 't', 'can', 'will', 'just', 'don', "don't", 'should', "should've", 'now', 'd', 'll', 'm', 'o', 're', \
            've', 'y', 'ain', 'aren', "aren't", 'couldn', "couldn't", 'didn', "didn't", 'doesn', "doesn't", 'hadn',\
            "hadn't", 'hasn', "hasn't", 'haven', "haven't", 'isn', "isn't", 'ma', 'mightn', "mightn't", 'mustn',\
            "mustn't", 'needn', "needn't", 'shan', "shan't", 'shouldn', "shouldn't", 'wasn', "wasn't", 'weren', "weren't", \
            'won', "won't", 'wouldn', "wouldn't"]

In [15]:
# Combining all the above statemennts 
from tqdm import tqdm
preprocessed_Summary = []
# tqdm is for printing the status bar
for sentance in tqdm(ddfff['Summary'].values):
    sent = decontracted(sentance)
    sent = sent.replace('\\r', ' ')
    sent = sent.replace('\\"', ' ')
    sent = sent.replace('\\n', ' ')
    sent = re.sub('[^A-Za-z0-9]+', ' ', sent)
    sent = ' '.join(e for e in sent.split() if e not in stopwords)
    preprocessed_Summary.append(sent.lower().strip())

100%|█████████████████████████████████████████| 14/14 [00:00<00:00, 552.79it/s]

In [16]:
# Combining all the above statemennts 
from tqdm import tqdm
preprocessed_Top_Skills = []
# tqdm is for printing the status bar
for sentance in tqdm(ddfff['Top_Skills'].values):
    sent = decontracted(sentance)
    sent = sent.replace('\\r', ' ')
    sent = sent.replace('\\"', ' ')
    sent = sent.replace('\\n', ' ')
    sent = re.sub('[^A-Za-z0-9]+', ' ', sent)
    sent = ' '.join(e for e in sent.split() if e not in stopwords)
    preprocessed_Top_Skills.append(sent.lower().strip())

100%|███████████████████████████████████████| 14/14 [00:00<00:00, 14017.73it/s]

In [17]:
# Combining all the above statemennts 
from tqdm import tqdm
preprocessed_experiance = []
# tqdm is for printing the status bar
for sentance in tqdm(ddfff['Experience'].values):
    sent = decontracted(sentance)
    sent = sent.replace('\\r', ' ')
    sent = sent.replace('\\"', ' ')
    sent = sent.replace('\\n', ' ')
    sent = re.sub('[^A-Za-z0-9]+', ' ', sent)
    sent = ' '.join(e for e in sent.split() if e not in stopwords)
    preprocessed_experiance.append(sent.lower().strip())

100%|█████████████████████████████████████████| 14/14 [00:00<00:00, 423.97it/s]

In [18]:
ddfff.drop(['Top_Skills','Summary','Experience'],axis=1,inplace=True)

In [19]:
ddfff['Top_Skills']=preprocessed_Top_Skills
ddfff['Summary']=preprocessed_Summary
ddfff['Experience']=preprocessed_experiance

In [20]:
ddfff.head(2)

,Name,Top_Skills,Summary,Experience
0,Abir Chowdhury,peoplesoft time labor,having 6 years it relevant experience peopleso...,oraclesenior application engineerjuly 2019 pre...
1,Ananya Brata Datta,client issue resolution team management progra...,accomplished oracle erp consultant 8 years ind...,soaisteam leadfebruary 2012 present kolkata ar...

In [21]:
ddfff.to_csv('cv_details_processed.csv')